Fix PublicationState in VideosRequestParameters
MovingImage24/VMProApiClient pull request #35
Opened 2017-11-15 15:33 UTC by pavlepredic

PublicationState property in VideosRequestParameters is not supposed to be a boolean, but a string, containing one of the following values:
- published
- not_published
- all

2017-11-16 09:30 UTC, robertszeker commented on lib/Util/SearchEndpointTrait.php
> +                case 'published':
Looks like publicationState inside $parameters can have any value. Does it make sense to add a check inside VideosRequestParameters->setPublicationState() to avoid that? Like we did for VideosRequestParameters->setOrder()

2017-11-16 09:30 UTC, robertszeker commented on lib/Util/SearchEndpointTrait.php
> +                case 'published':
What I actually don't like: it seems so that you can set any value when calling VideosRequestParameters->setPublicationState(), but you have to check SearchEndpointTrait to see what values make sense.

2017-11-16 09:32 UTC, pavlepredic commented on lib/Util/SearchEndpointTrait.php
> +                case 'published':
Yeah, I guess we could add some validation to the setPublicationState method

2017-11-20 10:02 UTC, robertszeker approved these changes

2017-11-21 10:58 UTC, kenloburn requested changes

2017-11-21 10:58 UTC, kenloburn commented on lib/Entity/VideosRequestParameters.php
> +        $pool = ['published', 'not_published', 'all'];
Create constants for this

2017-11-21 10:58 UTC, kenloburn commented on lib/Util/SearchEndpointTrait.php
> +                case 'published':
Seconded, plus use constants :)

2017-11-24 09:44 UTC, kenloburn approved these changes

2017-11-24 09:47 UTC, merged